baseURL = "https://ucsb-game-dev-club.github.io/"
languageCode = "en-us"
title = "UCSB Game Development Club"
theme = "ucsb-gamedev"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
