#!/bin/bash
# This script builds and publishes the website to master branch.

# Print all commands executed, halt on error
set -x +e

# Generate site (will be placed in /public)
hugo

PUBLISH_DIR=master_sync
if [[ ! -d "$PUBLISH_DIR" ]]; then
    git clone git@github.com:ucsb-game-dev-club/ucsb-game-dev-club.github.io "$PUBLISH_DIR"
fi
cd "$PUBLISH_DIR" && \
    git reset --hard HEAD && \  # Make sure we have a "fresh" copy of the repository.
    git clean -f -d && \
    git checkout master && \    # We might not be on master, so make sure it's checked out.
    git pull && \
    git rm * -r && \            # Ensure that deleted pages stay deleted, because
    cp -r ../public/* . && \    # we will add the new files generated by hugo.
    git add . && \              # If there's no change to a file, it will not show as changed.
    git commit -m "Update site (autogenerated commit using publish.sh)" && \
    git push origin master
